In [ ]:
import numpy as np
import matplotlib.pyplot as plt

n=int(input("ingrese el tamaño de la zona de estudio: "))
zona= np.random.randint(0,100,size=(n,n))
frecuencia=zona.astype(str)

for i in range(len(zona)):
    for e in range(len(zona[i])):
        if zona[i,e] <=2:
            frecuencia[i,e]="D"
        elif zona[i,e] > 2 and zona[i,e]<=15:
            frecuencia[i,e]="M"
        elif zona[i,e]<=30:
            frecuencia[i,e]="F"
        elif zona[i,e] <60:
            frecuencia[i,e] = "MF"
        else:
            frecuencia[i,e] = "T"

Estados=["D","M","F","MF","T"]
cantidad=[]

for i in Estados:
    cantidad.append(str(np.count_nonzero(frecuencia == i)))
print(zona)
media=np.mean(zona)
mediana=np.median(zona)
desviacion=np.std(zona)
moda=max(cantidad)
plt.bar(Estados,cantidad)
print("\nmedia: ",media,"mediana: ",mediana,"Moda: ",moda,"desviacion: ",desviacion,sep="\n")

plt.show()



ingrese el tamaño de la zona de estudio: 4
[[10 33  7 29]
 [ 8 65 91 32]
 [53 46 97 26]
 [26 74 39 33]]

media: 
41.8125
mediana: 
33.0
Moda: 
6
desviacion: 
26.7773662586521
