In [2]:
import numpy as np



n=int(input("ingrese n: "))
m=int(input("ingrese m: "))
matriz=np.random.randint(0,1000, size=(n,m))
matriznueva=matriz.astype(str)
print(matriz)

for i in range(len(matriz)):
    for e in range(len(matriz[i])):
        if matriz[i,e] >=500:
            matriznueva[i,e]="🟥"
        elif matriz[i,e] <500 and matriz[i,e] >= 250:
            matriznueva[i,e]="🟨"
        else:
            matriznueva[i,e]="🟩"
print(matriznueva)



ingrese n: 4
ingrese m: 4
[[940 976 139 498]
 [ 29  33 815 303]
 [487 147  10 145]
 [251 118 503 621]]
[['🟥' '🟥' '🟩' '🟨']
 ['🟩' '🟩' '🟥' '🟨']
 ['🟨' '🟩' '🟩' '🟩']
 ['🟨' '🟩' '🟥' '🟥']]
